axibase/atsd

api/meta/entity/metrics.md
api/meta/metric/create-or-replace.md
api/meta/metric/examples/fetch-metrics-by-limit-parameter.md
api/meta/metric/examples/list-active-metrics.md
api/meta/metric/examples/list-metrics-by-maxinsertdate.md
api/meta/metric/examples/list-metrics-by-mininsertdate.md
api/meta/metric/examples/list-metrics-by-name-and-tag.md
api/meta/metric/examples/list-metrics-by-name.md
api/meta/metric/examples/list-metrics-with-tag-table.md
api/meta/metric/get.md

`retentionInterval` field was renamed to `retentionDays` in revision 14543 (2016-10-28), but the examples in documentation are still using the old name.

changed `retentionInterval` field to `retentionDays`

---

administration/ssl-configure.md

Keystore can be created only after the certificate was created.

ssl-configure.md 

---

rule-engine/functions.md

Pipe char `|` was processed as table row delimiter.

Conditional Functions markdown fixes

---

rule-engine/notifications/web-driver.md

I think that adding a special instruction for installing web driver inside Docker container will not be superfluous. There are two main differences:
1) Inside the container the commands should be executed from root user
2) There is no sudo available
How should these instructions be structured?

Updated web driver installation steps

---

api/data/series/group.md

Remove statement that group period is inherited from aggregate period in case when group period is not explicitly specified.

Change group period description.

---

api/data/series/query.md

Remark. 
I reordered paragraphs ## Control Fields and ## Transformation Fields,
because in the request description ordering of the query fields is
`filter, process, control`.

Add "valueFiltr" description, and reorder two sections.

---

rule-engine/condition.md

`hourOfDay()` returns `org.joda.time.DateTime$Property` object, while `getHourOfDay()` returns `int`

fixed time condition

---

rule-engine/resources/url_avail.sh

currently, script execution fails if it does not exit within 15 sec. reporting a rule error

add 10 second limit for curl

---

integration/scollector/scollector-startup.md
integration/tcollector/README.md
integration/tcollector/resources/tcollector
integration/tcollector/resources/tcollector.service

Some default collector scripts from tcollector distribution expect certain applications and Python modules to be installed. Do we need to document them? And do we need to review last two sections of this instruction?

Tcollector and scollector instructions update

---

api/data/series/query.md

In Data API > series query > tag filter field described so:
`Object with name=value fields.` 
I changed that to
`Object with name:value fields.` 
because actual delimiter used in series query is a colon symbol.

Fix delimiter in tag key-value pair.

---

api/data/series/query.md

Clearly state that wildcards may be used with LIKE, and NOT LIKE operators, and may not be used with comparison operators =, >, etc.

Refine usage of wildcards in tag expression.

---

.spelling
architecture.md
editions.md
history.md
pricing.md
schema.md

Mostly lint-tier errors, nothing was glaring. I know we typically tend to avoid instances of "we" but I thought for `history.md` it was appropriate to scuttle that rule.

Root pages refactor

---

.travis-functions.sh

Spellchecker script fix

---

rule-engine/object-datetime.md

* Unification of Example Table and Fields Table.
* Add on about accessing `DateTime` objects via Time Function or Window Fields + links.

object-datetime-refactor

---

.travis-functions.sh

We need to keep old yaspeller version (recent is 5.0.0).
In the latest version the workaround I created for dictionaries (a python script in docs-util) doesn't work. The patterns are preprocessed the same way as in spellchecker, but if the suggested replacement includes more than one word, the replacement candidate doesn't match the white list patterns.

Freeze yaspeller version

---

.linkcheck-config.json

Adds links from `atsd-use-cases` read as dead although they are active.

linkcheck-update

---

.travis-functions.sh

As Ken already added the links from atsd-use-cases here, let's use this white list for all repositories if it  does not exist in the repo.
The question is, should we  put invalid links to this list (e.g. https://catalog.data.gov/dataset/food-insecurity-rates-2009-present) together with ones that cause false-positive result for linkchecker?

Use atsd link whitelist for linkcheck for all repos

---

.linkcheck-config.json
integration/data-applications/README.md

I didn't update image links or move images when I moved `data-applications.md` so they are dead.
The `apache.org` link from the same page is also being read as dead, so I added it to the exception list.

data-applications-lint

---

rule-engine/window-fields.md

I read through the diff and the only line that seemed to be omit necessary info was the one you pointed out. I think this was caused by merging a short PR while the time refactor PR was still in progress.

time-refactor-2

---

tutorials/getting-started.md

@rodionos It occurred to me after opening this PR you might have meant only to include Getting Started "Chapter" names as opposed to "Chapter" and "Section" names. The current PR only removed "Sub-section" names but left in "Section" Names.

getting-started-toc

---

integration/README.md

Extension of Integration ToC to include each type of integration in Use Cases.
* Build is expected to fail, until [this PR](https://github.com/axibase/atsd-use-cases/pull/344) is merged.
* EDIT: For some reason we're getting a green check.

atsd-integration-toc

---

.linkcheck-config.json

* Add two Federation of American Scientists links to `linkcheck` document, because they are causing build related to a [Use Cases PR](https://github.com/axibase/atsd-use-cases/pull/372) to fails.

linkcheck-add-on

---

.linkcheck-config.json

A new link is coming up dead according to CI, it is [confirmed](https://www.bea.gov/regional/bearfacts/pdf.cfm?fips=15000&areatype=STATE&geotype=3) working.

new-link-add-on

---

administration/monitoring-metrics/rule-engine.md

looks like "hard-coding" is coming up misspelled. Everywhere I've looked has it written differently though: "hardcoding," "hard coding," and "hard-coding." which variant should we use?

hard-coding

---

changelogs/2018_nov/README.md

November 2018 Change Logs.
I removed the two Charts tickets because they were related to some support tasks one of the the interns was doing.
Because the number of Features and Bugs usually ends up changing a bit, I didn't update the Change Tracker chart.

nov-change-logs

---

api/network/README.md
api/network/message.md

Debug command actually prints error message, and this behavior is relied on in API tests.
Network command `message` prints error message if tags or message is not found, since rev. 22271.
HTTP API Message Insertion still swallows the errors silently.

Updated debug and message commands behavior

---

.linkcheck-config.json

Ignore links that can be opened only with JavaScript enabled and AdBlock off

Ignore links 

---

.travis.yml

Reverts axibase/atsd#580
Link checking in the whole project must be enabled on schedule

Revert "disable link checking in master branch"

---

.linkcheck-config.json

`linkcheck` tests patterns for exclusion using `find` method instead of `match`, so the patterns can be simplified.
Also mysql.com (socket error, but the domain will hardly disappear) and web.archive.org (slow) added to exclusion list

Link exclusion patterns refactoring

---

sql/examples/partition-lag.md

We have two identical queries in docs with different output. It seems that one of them was accidentally copied from another one https://axibase.com/docs/atsd/sql/examples/partition-lag.html#lag

Fix error in query with lead

---

sql/README.md

Also we use `createdDate` in API documentation but`creationTime` in SQL example.
Maybe we should add notice about it.

Fix URL to atsd entities fields page

---

.vuepress/config.js
.vuepress/theme/Layout.vue
.vuepress/theme/NavLinks.vue
.vuepress/theme/Navbar.vue
.vuepress/theme/util.js

Allow to customize navbar and homepage link for specific routes, e.g. /finance/.
Remove navbar links for `/finance/` pages, set home link to `/docs/atsd/finance/`.

Support per-route navbar links and home href

---

.vuepress/config.js
.vuepress/theme/ContactUs.vue
.vuepress/theme/Home.vue
finance/ru/README.md

Configuration properties:
* `url` - form submission POST endpoint, `/feedback/`
* `title` - form title, default `Contact Us`
* `content` - if string value is set, send given value instead for user's message
* `submitText`, `firstNameText`, `lastNameText`, `emailText`, `companyText`, `messageText` - override form field labels for l10n
* `errorText` - message if submission failed, default `Something went wrong, please, try again later`
* `successText` - message on success, default `Submitted successfully`
Configuration may be set in `config.js::themeConfig.feedback` or `contactUs` option in frontmatter. Also you can use `contactUs: true` for default form. Form is shown only if page is landing and `contactUs` is present in frontmatter

Add 'Contact Us' form to landing page

---

.vuepress/theme/Home.vue
.vuepress/theme/enhanceApp.js
.vuepress/theme/tracknav.js

Tracks are sent with from/to parameters, as well as `section=contact-us` parameter to filter this clicks in messages list.
This solution introduces some duplication, but it cannot be removed until an issue will be fixed in vue-router (issue 1668)

Track clicks to `Request Trial` link

---

finance/ru/ConsumerLatencyParser.java

Resolves [#165](https://github.com/axibase/moex-consumer/issues/165)
This version consumes twice less memory and allows to parallelize parsing and calculation. Parsing parallelization is performed on file level, calculation – on series level. Use `-DioThreads=N` and `-DcalcThreads=N` to control how many threads to be assigned to which task. Default is 1. Use `0` to use `ForkJoinPool.commonPool()` and assign work to all available threads.
After parsing stage, total number of samples, total memory consumed on data in MBs, and memory consumed for 1 metric, are reported.
On DMA, all logs but logger_hc_jdk:statistics are processed in parallel with `-Xmx=4G`, stock market statistics – `-Xmx=6G` with parallel parse, single-thread calculate.

ConsumerLatencyParser: Concurrent implementation

---

finance/ru/ConsumerLatencyParser.java

Currently there is an assertion error if there are one or two files processed, and already allocated space is greater than required

ConsumerLatencyParser: Fixed Spectra processing
