axibase/atsd

installation/firewall.md
+ Added iptables-persistent package and instructions on how to use it
~ Modified original script to not use echo to create the scripts and to use full paths to iptables-(restore,save)
=> Updated debian section

api/data/alerts/examples/history-query/alerts-history-query-defined-metric.md, api/data/alerts/examples/history-query/alerts-history-query-defined-rule.md, api/data/alerts/examples/history-query/alerts-history-query-enddate-interval.md, api/data/alerts/examples/history-query/alerts-history-query-entity-expression-entity-properties.md, api/data/alerts/examples/history-query/alerts-history-query-entity-expression-entity-tags.md, api/data/alerts/examples/history-query/alerts-history-query-entity-expression-name.md, api/data/alerts/examples/history-query/alerts-history-query-entity-group.md, api/data/alerts/examples/history-query/alerts-history-query-entity-wildcard.md, api/data/alerts/examples/history-query/alerts-history-query-last-day.md, api/data/alerts/examples/history-query/alerts-history-query-limit.md, api/data/alerts/examples/history-query/alerts-history-query-message-commands.md, api/data/alerts/examples/history-query/alerts-history-query-metric-wildcard.md, api/data/alerts/examples/history-query/alerts-history-query-metrics-all-value.md, api/data/alerts/examples/history-query/alerts-history-query-multiple-entity.md, api/data/alerts/examples/history-query/alerts-history-query-multiple-queries-limit.md, api/data/alerts/examples/history-query/alerts-history-query-multiple-queries-unknown-entity.md, api/data/alerts/examples/history-query/alerts-history-query-multiple-queries.md, api/data/alerts/examples/history-query/alerts-history-query-property-commands.md, api/data/alerts/examples/history-query/alerts-history-query-rule-wildcard.md, api/data/alerts/examples/history-query/alerts-history-query-rules-all-value.md, api/data/alerts/examples/query/alerts-query-entity-expression-entity-properties.md, api/data/alerts/examples/query/alerts-query-entity-expression-entity-tags.md, api/data/alerts/examples/query/alerts-query-entity-expression-name.md, api/data/alerts/examples/query/alerts-query-metrics-all-value.md, api/data/alerts/examples/query/alerts-query-multiple-queries-unknown-entity.md, api/data/alerts/examples/query/alerts-query-multiple-queries.md, api/data/alerts/examples/query/alerts-query-rules-all-value.md, api/data/alerts/history-query.md, api/data/alerts/query.md
Some examples will need to write after removing bugs
=> alerts examples

api/sql/README.md, api/sql/examples/regularize.md
=> English Corrections

api/sql/README.md
=> SQL: fix datetime format in columns description

change-logs/weekly-2016/12-19-through-12-25/README.md
=> change-log

api/sql/README.md, api/sql/examples/lookup.md
* LOOKUP.md
* numeric precedence section from README.md
=> sql-changes

integration/matlab/README.md
added info about tables with dots in their name (MatLab)
=> MATLAB Integration fixes

administration/migration/cluster.md
Should change Java classpath in order to run the TableCloner.
=> Fix Java classpath.

api/sql/README.md
I looked up "containing query" and didn't really see anything so that's the reason I chose to change it here. 
This is an awesome feature.
=> Inline Views

changelogs/2017_31/README.md
These change logs were a challenge for me, I really felt like I didn't understand enough about what was done to accurately re-write descriptions. Please let me know which links you'd like me to show in the various feature descriptions that I left empty. sections marked with ** asterisks are sections that I left unchanged.
=> Change Logs 31

api/data/series/aggregate.md, api/data/series/group.md, api/data/series/rate.md
Update documentation for the group/rate/aggregate processors:
- add "order" field to the "rate" function;
- add description of the grouping process;
- add example of interpolation during grouping.
=> Group-rate-aggregate updates.

rule-engine/functions-text.md
=> Fixed keepBeforeLast function case

rule-engine/condition.md, rule-engine/filters.md, rule-engine/placeholders.md, rule-engine/variables.md
Added note about quote escaping into variables.md and links to data type section of this document from the others.
=> Add note about quote escaping

rule-engine/entity-fields.md, rule-engine/functions-lookup.md, rule-engine/functions.md
Documented according to 4949.
File `entity-fields.md` contains fields from [Data API list](https://github.com/axibase/atsd/blob/master/api/meta/entity/list.md#fields) and [printObject()](https://apps.axibase.com/redmine/issues/4955#note-2) table which were accessible during tests.
If this file is useful, then I'll fill in empty lines.
=> getEntities description

rule-engine/functions-rules.md, rule-engine/functions.md
Documented according to 4925. No fields are accessible for the returned objects.
=> rule_windows() description

rule-engine/functions-db.md
Notes about empty tags search and timestamp field.
=> Note about empty tags

rule-engine/derived.md, rule-engine/functions-collection.md, rule-engine/functions-lookup.md, rule-engine/functions-property.md, rule-engine/functions-text.md, rule-engine/variables.md
Changes according to https://apps.axibase.com/redmine/issues/4949#note-18
=> [ ] replaced with get()

rule-engine/functions-rules.md
5115 Rule Engine: rule_window fields
4925 Rule Engine: rule_window function
=> Rule functions 

changelogs/2018_03/README.md
Not documented:
**Issue**| **Category**    | **Type**    | **Subject** 
---|---|---|---
5103 | monitoring | Bug | Simon console doesn't work.
5036 | admin | Feature | Backup multiple record types from zip/tar.gz archive.
4909 | security | Support | Install DV SSL certificate from Lets Encrypt CA.
5140 | UI | Bug | Empty page on opening simon console.
=> Links added

administration/metric-persistence-filter.md, configuration/functions-entity-groups-expression.md
Metric Persistence Filter can be built using functions from Math class.
=> Note about Math functions

.travis.yml
Same changes as in https://github.com/axibase/atsd-use-cases/pull/216
=> .travis.yml refactoring

.markdownlint.json, .travis-functions.sh, .travis.yml
* Move preparation steps to a single function
* Add markdownlint config file
=> Travis refactoring [WIP]

.travis-functions.sh
Fixed accumulated dictionary generation if dictionary file doesn't end with a new line character
=> Fixed accumulated dictionary generation

api/data/filter-entity.md, configuration/entity_groups.md, configuration/functions-entity-groups-expression.md
Some functions from [Entity Groups](https://github.com/axibase/atsd/blob/master/configuration/entity_groups.md#supported-functions) expression are supported in `entityExpression` of series API query.
=> Update supported functions in entity filter

.vuepress/theme/Page.vue, .vuepress/theme/SearchBox.vue
* Move nav links right
* Remove back/forward links to external resources
=> UI Changes

changelogs/2018_05/README.md, changelogs/README.md
Omitted issues: 5283, 5312, 5273, 2346 (charts)
=> may-change-logs

tutorials/getting-started-alert.md, tutorials/getting-started-export.md, tutorials/getting-started-insert.md, tutorials/getting-started-portal.md, tutorials/getting-started-sql.md, tutorials/getting-started.md
Review of Getting Started articles for style and grammar.
=> getting-started-style-changes

api/data/ext/csv-upload.md
* added a missing `#` in a reference link.
=> add-prefix

sql/examples/sql-report.csv
=> remove-extra-quote.

administration/README.md, administration/server-properties.md, administration/ssl-lets-encrypt.md, api/data/ext/csv-upload.md, api/network/message.md, changelogs/2016_03/README.md, changelogs/2017_41/README.md, installation/docker-redhat.md, installation/docker.md, installation/ldap/jxplorer.md, integration/graphite/installation.md, integration/graphite/storage-finder.md, integration/nmon/scheduled-file-upload.md
scheduled-file-upload.md fixed
credentials, passwords changes
`Let's Encrypt` excluded from checks
=> Fixes to pass the rules

.vuepress/config.js
API links menu removed from navbar
* REST and Network API links placed into navbar separately
* API Clients moved to REST API page menu
=> Change API links location

configuration/functions-entity-groups-expression.md, rule-engine/functions-collection.md, rule-engine/functions-date.md, rule-engine/functions-forecast.md, rule-engine/functions-format.md, rule-engine/functions-link.md, rule-engine/functions-lookup.md, rule-engine/functions-message.md, rule-engine/functions-property.md, rule-engine/functions-random.md, rule-engine/functions-rules.md, rule-engine/functions-security.md, rule-engine/functions-series.md, rule-engine/functions-sql.md, rule-engine/functions-statistical.md, rule-engine/functions-table.md, rule-engine/functions-text.md, rule-engine/functions-utility.md, rule-engine/functions-value.md, rule-engine/functions-web-query.md, rule-engine/functions.md
This PR contains the requested changes from Issue #5454:
* Remove leading whitespace from fenced text (there was a lot).
* Alphabetize `functions.md`.
=> requested-changes

api/data/series/aggregate.md
Document that aggregation period is optional. Up to now it was obligatory.
=> Aggregation period

api/data/properties/delete.md
=> requested-review

administration/backup.md, administration/passwords-obfuscation.md, administration/replication.md, integration/spss/statistics/README.md, tutorials/getting-started-portal.md, tutorials/getting-started.md
=> remove-article

api/meta/entity/delete.md
=> entity-delete-review

sql/sql-console.md
Refactor of  `sql/sql-console.md`.
=> sql-console-refactor

sql/client/README.md
Refactor of `/sql/client/README.md`
=> sql-client-refactor

sql/README.md, sql/examples/filter-by-date.md
I am going to reference [Rule engine docs](https://github.com/axibase/atsd/pull/695), but that PR is not merged yet.
=> Document is_workday and is_weekday

rule-engine/window-fields.md
* A few minor changes but nothing significant for flow/grammar.
* Added mention of **On Open** behavior for `alert_duration*` fields.
=> window-fields-review

.travis-functions.sh, changelogs/2018_jul/README.md, changelogs/2018_jun/README.md, rule-engine/window.md, tutorials/getting-started-alert.md
Fixed anchors validation on pull requests
=> Fixed links

sql/README.md
* Refactor of `IS_WEEKDAY` and `IS_WORKDAY` functions in `sql/README.md`
=> sql-functions-refactor

.travis-functions.sh
This PR should fix atsd-api-python repo
=> Give repo information to local link validator

.linkcheck-config.json, administration/compaction/atsd.md, reporting/README.md, reporting/ad-hoc-exporting.md, reporting/export-url.md, reporting/scheduled-exporting.md
* Refactor and review of `/reporting` directory.
* Update of `linkcheck` file to include additional `apache.org` URLs which are intermittently read as dead.
=> exporting-data

shared/scheduling.md
* `cron` expression examples from [Scheduling](https://axibase.com/docs/axibase-collector/scheduling.html#cron-expression-examples) copied to ATSD Docs. 
* I also copied Field Control Symbols and Field Constraints [tables](https://axibase.com/docs/axibase-collector/scheduling.html#cron-expressions) because they are relevant.
=> cron-expression-examples

.linkcheck-config.json
This PR adds a couple of specific and wildcard URLs to the linkcheck document which were coming up dead.
=> linkcheck-update

README.md, administration/support.md, changelogs/2017_nov/README.md, changelogs/2017_sep/README.md, changelogs/2018_aug/README.md, changelogs/2018_oct/README.md, changelogs/2018_sep/README.md, integration/data-applications/cross-filter.md, integration/data-applications/data-slider.md, portals/README.md, portals/portals-overview.md, portals/selecting-series.md
Refactor old GitHub links to new static site links.
=> charts-docs-links-refactor-ATSD

api/data/ext/examples/DataApiCommandInsertExample.java, api/data/messages/examples/DataApiMessagesQueryExample.java, api/data/properties/examples/DataApiPropertiesQueryExample.java, api/data/series/examples/DataApiSeriesCsvInsertExample.java, api/data/series/examples/DataApiSeriesQueryExample.java
* all streams were wrapped to try with resources
* setting of content-length removed
* set charset for conversion implicitly
=> [Dev] java examples refactor

changelogs/2016_dec/README.md, changelogs/2016_nov/README.md, changelogs/2017_apr/README.md, changelogs/2017_dec/README.md, changelogs/2017_feb/README.md, changelogs/2017_jan/README.md, changelogs/2017_mar/README.md, changelogs/2017_may/README.md, changelogs/2017_nov/README.md, changelogs/2017_oct/README.md, changelogs/2018_aug/README.md, changelogs/2018_sep/README.md
Related to requested changes in #5775.
=> charts-change-log-links

api/data/series/query.md
Add description of minInsertDate and maxInsertDate settings of Series Query.
=> Add description of  setting of Series Query.

api/data/series/forecast.md
Describe auto-aggregation settings in series query forecast.
=> Describe auto-aggregation settings in series query forecast.

.dictionary-names, integration/aer/README.md
Added new name to dictionary to fix spellcheck
=> Updated dictionary names

api/data/series/forecast.md
Add description of `baseline` forecasting in api.series.query.forecatsing.
=> Baseline forecasting.

.linkcheck-config.json
This should fix axibase-charts travis builds
=> Researchgate responses 403 from travis datacenter

.vuepress/theme/styles/config.styl, .vuepress/theme/styles/mobile.styl, .vuepress/theme/styles/theme.styl
=> Change sidebar font size and content margin

.vuepress/config.js, .vuepress/theme/enhanceApp.js
Send navigation tracks to `/tracknav/`
=> Add navigation tracking

.vuepress/theme/Home.vue, .vuepress/theme/Layout.vue
1. Remove HTML escaping for feature details block
2. Fix NPE when navigating from landing page, page ref is null because of custom layout
=> Update landing page template

.vuepress/config.js, .vuepress/theme/ContactUs.vue
Parameters are: `firstName`, `lastName`, `company`, `email`, `message`
=> Change feedback url, change url parameters

finance/ru/ConsumerLatencyParser.java
LatencyParser updated to support short datetime format of SendingTime, ReceiveTime, ProcessTime
=> LatencyParser updated
